### ISSUE TITLE
Vanilla local setup on Ubuntu fails

### ISSUE THREAD

**Issue by the-mx** [opentensor/bittensor-subnet-template#49]
Following the `running_on_staging.md`.

Blockchain node runs. No errors except one:
> Error while running root epoch: "Not the block to update emission values."

Miner log has errors:

> 2024-01-18 07:44:15.992 |      DEBUG       | axon     | <-- | 827 B | Dummy | 5FvVLxkyoKsLmnXAqZaap1Bp6HxLSzzg6p58DEiwd1Eva8q7 | 127.0.0.1:52292 | 200 | Success 
> 2024-01-18 07:44:15.993 |      ERROR       | NotVerifiedException: Not Verified with error: Signature mismatch with 3542913964592439.5FvVLxkyoKsLmnXAqZaap1Bp6HxLSzzg6p58DEiwd1Eva8q7.5E7yNCEsJZdFKRV4qeZcdYuDX54tJ2ysoK8uPXd1ZUVQ2eQD.d6cd9c9c-b5cc-11ee-9ac9-a8a1591a7c9f.a7ffc6f8bf1ed76651c14756a061d662f580ff4de43b49fa82d80a4b80f8434a and 0x7a9ee7e33388e0d410692f08470c2fbafc4168072606b58e4fed369e29808c2e84b4ad66bac5fba2f421093de5177b96cf63c0596793dc3f14be8fbfe80df388

Validator log has errors:
> 024-01-17 15:17:02.118 |      ERROR       | Error during validation       'Validator' object has no attribute 'moving_averaged_scores'
Traceback (most recent call last):
File "/home/bittensor-subnet-template/template/base/validator.py", line 141, in run
   self.sync()
 File "/home/bittensor-subnet-template/template/base/neuron.py", line 121, in sync
   self.set_weights()
 File "/home/bittensor-subnet-template/template/base/validator.py", line 220, in set_weights
   self.moving_averaged_scores, p=1, dim=0
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Validator' object has no attribute 'moving_averaged_scores'

After commenting out `set_weights` method, I see these messages:
> 2024-01-18 07:44:31.871 |      DEBUG       | dendrite | --> | 3068 B | Dummy | 5E7yNCEsJZdFKRV4qeZcdYuDX54tJ2ysoK8uPXd1ZUVQ2eQD | 77.237.52.204:8091 | 0 | Success
2024-01-18 07:44:31.876 |      DEBUG       | dendrite | <-- | 3221 B | Dummy | 5E7yNCEsJZdFKRV4qeZcdYuDX54tJ2ysoK8uPXd1ZUVQ2eQD | 77.237.52.204:8091 | 503 | Service at 77.237.52.204:8091/Dummy unavailable.

Important!
I'm running both neurons on a single node.

**Comment by the-mx** [comment]
Fixed

**Comment by amrendraw3** [comment]
What was the fix for this?
