### ISSUE TITLE
add loguru to requirements.txt 

### ISSUE THREAD

**Issue by surcyf123** [opentensor/bittensor-subnet-template#82]
https://github.com/opentensor/bittensor-subnet-template/blob/332a4177b6ad85fcf421600758618d9bc4a8b207/template/utils/config.py#L23

This import imports from loguru, yet when you install the repo, loguru does not get installed as it's not in the requirements.txt file.

**Comment by ibraheem-opentensor** [comment]
We have depreciated `loguru` and integrated bittensor's logging
